# -*- coding: utf-8 -*-
"""Lab01_pandas_and_matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17JcdDP8dD0DjpgpFFyC50Vco4xjWvKIa

## Learning Pandas and Matplotlib

Pandas is Pythons library that enables broad possibilities for data analysis.
By using Pandas it is very easy to upload, manage and analyse data from different tables by using SQL-like commands. Moreover, in connection with the libraries Matplotlib and Seaborn, Pandas gives broad possibilites to visualise the data.
"""

#First import the libraries/packages we need
import pandas as pd
import numpy as np

from matplotlib import pyplot as plt
from matplotlib.pyplot import rcParams
rcParams['figure.figsize'] = 8, 5
import seaborn as sns

"""We study the main methods of Pandas and Matplotlib packages by working with the dataset that describes the churn rate of the customers of a telecom company.

<b>Exercise 1:</b>

Read the data from the file 'telecom_churn.csv' and display the first 5 rows by using the method 'head'. <b> Hint :</b> The method read_csv can be useful
"""

### Write Your code here ###

"""<b>Exercise 2:</b>

Display the size of the data array, information about it, and its main statistical characteristics. <b>Hint:</b> use methods shape, info, describe.
"""

### Write Your code here ###

"""<b>Exercise 3:

</b>Convert the column 'Churn' to the int64 type. <b> Hint:</b> use the astype method 

Plot the distribution of the churn and  loyal clients in the bar plot. The figure should look like this:

<img src="dist_churn.png">
"""

### Write Your code here ###

"""### Sorting

<b>Exercise 4:</b>

Sort the dataframe you have obtained in exercise 3 by the value in 'Total day charge' in descending/ascending order.
Also sort it by using the column 'Churn' as the primary key and 'Total eve calls' as the secondary key. Try different combinations of ordering. 

<b> Hint:</b> use the method sort_values
"""

### Write Your code here ###

"""### Indexing and extracting information from the dataframe

By using Pandas dataframes we are able to index and extract information from the dataset. You can index the information stored in dataframe either by names or by indices. In the first case you use the command loc, in the second iloc. 

<b> Hint: </b> Use logical indexing for the columns and the groupby method to solve the tasks.

<b>Exercise 5:</b>
* Display the mean churn rate of the clients.
* Now we want to analyse statistical information only for the clients, which are or aren't loyal to their telecom-company (field 'Churn' in dataframe). Extract the loyal and non-loyal clients from the table separately and display the means of their charateristics in a single dataframe.
* How long do the non-loyal users talk during the day (on average)?
* What is the maximum length of the international calls for the loyal users that do not use the international plan?
"""

### Write Your code here ###

"""### Distribution of the features

<b>Exercise 6:</b>

Plot the distribution of the features that have numerical values. 

<b> Hint: </b>use the method hist which can also be applied from the pandas dataframe. It should look like that:
<img src="hist_feat.png">

What do you observe? From which probability distribution could each feature be generated?
"""

### Write Your code here ###

"""### Pivot tables and graphics

We want to see how the instances are distributed between two categories: 'International plan' and 'Churn'. 

<b>Exercise 7:</b>
* Build the cross table between the features using the method <i>crosstab</i>.
* Visualize the distribution for the feature 'Churn', depending on the value of the features 'International plan', 'Voice mail plan', and 'Customer service calls'.
<b>Hint:</b> Use commands plt.sublot and sns.subplots.

Your plot should look something like this:
<img src="dist_crosstab.png">

What do you see? What conclusions can be drawn? What feature (intuitively) can be more important for Churn prediction?
"""

### Write Your code here ###

"""<b>Exercise 8:</b>

Add a new feature to the dataframe which will describe whether or not the user has done more than 3 service calls. Investigate how this feature describes the churn rate.
"""

### Write Your code here ###